### ISSUE TITLE
Jump pop-up msg shows incorrect miles to go

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#333]
Jump pop-up message showed “x miles to go” message - 'x' miles value not consistent with the mission length.

E.g. For missions of 0.5 miles length, it showed 2.94 miles to go in the pop-up. This was reported by 3 / 16 CMSC434 undergrads.

![jump_miles](https://cloud.githubusercontent.com/assets/2873216/19205981/bd49d690-8cb3-11e6-8f52-d1b53ab76781.png)

**Comment by manaswis** [comment]
Further evidence from my own testing:

"2.87 miles to go" -- Way more than 0.5 miles
<img width="1280" alt="jump-popup-1" src="https://cloud.githubusercontent.com/assets/2873216/19244779/edf52fd0-8eeb-11e6-80d7-f04ef51c7ff5.png">

Miles again incorrect - see annotation in the image below
<img width="1276" alt="jump-popup-2" src="https://cloud.githubusercontent.com/assets/2873216/19244780/edff4a06-8eeb-11e6-943f-84f5431805b3.png">

This isn't consistent with the above examples.
<img width="1280" alt="jump-popup-3" src="https://cloud.githubusercontent.com/assets/2873216/19244781/ee009b4a-8eeb-11e6-95ec-96eaecbafa2a.png">

The numbers shown are inconsistent with any formula. Would have look into how these miles are generated.

**Comment by Soben713** [comment]
This problem is fixed and explained in PR #349.

**Comment by jonfroehlich** [comment]
Why is this reopened?

**Comment by Soben713** [comment]
@jonfroehlich We are just discussing how to handle pull requests and when to close the issues. Manaswi suggested to use the `pull-request-submitted` label and keep the issues open until their pull requests are tested and merged to master. The pull request I submitted for this issue is not yet merged, so we reopened this.

**Comment by Soben713** [comment]
Also, we added a "Pull Request Submitted" column to the waffle page. So we can quickly manage everything. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/1576529/19448340/7773921e-946f-11e6-9508-86571518b0df.png)

**Comment by manaswis** [comment]
@Soben713 I was reviewing the PR #349. The bug isn't fixed. See screenshots - notes on the images.

<img width="1226" alt="pr333-review" src="https://cloud.githubusercontent.com/assets/2873216/19452419/f09a895e-947e-11e6-8432-4b82795ba259.png">
<img width="1256" alt="new_pr_review" src="https://cloud.githubusercontent.com/assets/2873216/19452596/954b092e-947f-11e6-9553-cb4233210bd3.png">

**Comment by Soben713** [comment]
@manaswis This seems to be exactly the same problem that I solved and it's very strange that you still have this problem. Are you sure that you tested the correct version of the code? Maybe you should run `grunt` or disable your browser`s cache first.

**Comment by manaswis** [comment]
Yeah, I didn't run grunt and that was the problem. I think the miles shown are now much closer to the actual. Only a few feet difference is there (due to rounding off errors), which is fine.
